from annotation.Annotation import Annotation
from annotation.AnnotationPair import AnnotationPair
from annotation.AnnotationPair import annotations_to_pairs, remove_pcr_duplicates, pairs_to_annotations_pick
from annotation.Motif import Motif
